---
deployment:
  tasks:
    - echo "Starting Deployment"
    - npm install
    - npm run build
    - rsync -av --delete build/ /home/asalodaf/repositories/asaloda-frontend/
    - echo "Deployment Finished"