export const ROUTES = {
    HOME: "/",
    NOT_FOUND: "*",
    DISCOUNTS: "/discounts",
    REVIEWS: "/reviews",
    PAYMENT_DELIVERY: "/payment_delivery",
    FAQ: "/faq",
    ABOUTUS: "/about-us",
    PARTNERSHIP: "/partnership",
    REGISTER: "/register",
    LOGIN: "/login",
    CONTACTS: "/contacts",
    MY_ORDER: "/my-order",
    ORDER: "/order/:id",
    PROGRAM: "/program/:id",
    ALL_ORDER: "/all-orders",
    PRIVACY_POLICY: "/privacy-policy",
    NOT_ALLOWED: "/forbidden",
};
